line-length = 120
exclude = [".git", "__pycache__", "build", "dist", ".venv"]

[lint]
ignore = [
  "E501",
  "W291",
  "W293",
  "E302",
  "E402",
  "E305",
  "E401",
  "F401",
  "E303",
  "E231",
  "E261",
  "E251",
  "E701",
  "F541",
  "F841",
  "I001",
  "S112",
  "BLE001",
  "PLW0128",
  "SIM222",
  "B015"
]